/**
1 - view
2 - create
3 - edit
*/

export enum Claims {
  // User
  SET_USER_ROLE = 'SET_USER_ROLE',

  // Settings
  VIEW_SETTINGS_SERVER = 'VIEW_SETTINGS_SERVER',
  CREATE_SETTINGS_SERVER = 'CREATE_SETTINGS_SERVER',
  EDIT_SETTINGS_SERVER = 'EDIT_SETTINGS_SERVER',

  // Statistics
  VIEW_STATISTICS = 'VIEW_STATISTICS',

  // Role
  VIEW_ROLE = 'VIEW_ROLE',
  CREATE_ROLE = 'CREATE_ROLE',
  EDIT_ROLE = 'EDIT_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',
  VIEW_CLAIMS = 'VIEW_CLAIMS',

  // Issue
  EDIT_ISSUE = 'EDIT_ISSUE',
}
